spring:
  application:
    name: wlcp-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_ADDRESS_PASSWORD}
    properties:
      mail:
       smtp:
         auth: true
         starttls:
           enable: true
server:
   port: 8082
eureka:
   client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}