spring:
  application:
    name: wlcp-api
  datasource:
    jdbcUrl: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  archive-datasource:
    jdbcUrl: ${ARCHIVE_DB_URL}
    username: ${ARCHIVE_DB_USER}
    password: ${ARCHIVE_DB_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: ${DB_SCHEMA}
  archive-liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: ${ARCHIVE_DB_SCHEMA}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_ADDRESS_PASSWORD}
    properties:
      mail:
       smtp:
         auth: true
         starttls:
           enable: true
server:
   port: 8082
eureka:
   client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}
security:
  jwt-secret: ${JWT_SECRET}