spring:
  application:
    name: wlcp-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mysql.jdbc.driver
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
server:
   port: 8082
eureka:
   client:
    serviceUrl:
      defaultZone: http://wlcp-discovery.local:8761/eureka/
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}