spring:
  application:
    name: wlcp-api
  datasource:
    url: jdbc:mysql://wlcp-api-db:3306/wlcp-api
    username: wlcp
    password: wlcp
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: wlcp-api
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://wlcp-discovery:8761/eureka/