spring:
  application:
    name: wlcp-api
  datasource:
    jdbcUrl: jdbc:mysql://wlcp-db-dev:3306/wlcp-api
    username: wlcp
    password: wlcp
  archive-datasource:
    jdbcUrl: jdbc:mysql://wlcp-db-dev:3306/wlcp-api-archive
    username: wlcp
    password: wlcp
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: wlcp-api
  archive-liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: wlcp-api-archive
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://wlcp-discovery-dev:8761/eureka/
security:
  jwt-secret: WlcpRocks!