spring:
  application:
    name: wlcp-api
server:
   port: 8082
eureka:
   client:
    serviceUrl:
      defaultZone: http://wlcp-discovery.local:8761/eureka/
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}